[package]
name = "loom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"

[dev-dependencies]
cargo-tarpaulin = "0.25.2"
grcov = "0.8.18"
